apiVersion: v2
name: authentik-stack
description: Authentik with CNPG database and OIDC blueprints for Kubernetes
type: application
version: 0.1.0
appVersion: "2025.10.3"

dependencies:
  - name: authentik
    version: "2025.10.3"
    repository: https://charts.goauthentik.io
