apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: {{ include "authentik-stack.database.fullname" . }}
  labels:
    {{- include "authentik-stack.componentLabels" (dict "context" . "component" "database") | nindent 4 }}
spec:
  instances: {{ .Values.database.instances }}
  affinity:
    enablePodAntiAffinity: true
    topologyKey: kubernetes.io/hostname
  bootstrap:
    initdb:
      database: authentik
      owner: authentik
  storage:
    size: {{ .Values.database.size }}
  backup:
    volumeSnapshot:
      className: {{ .Values.database.snapshotClassName }}
      online: true
      onlineConfiguration:
        waitForArchive: true
        immediateCheckpoint: true
  monitoring:
    enablePodMonitor: false
---
apiVersion: postgresql.cnpg.io/v1
kind: ScheduledBackup
metadata:
  name: {{ include "authentik-stack.database.fullname" . }}-weekly
  labels:
    {{- include "authentik-stack.componentLabels" (dict "context" . "component" "database") | nindent 4 }}
spec:
  schedule: {{ .Values.database.backupSchedule | quote }}
  backupOwnerReference: self
  cluster:
    name: {{ include "authentik-stack.database.fullname" . }}
  method: volumeSnapshot
