---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - democratic-csi.yaml
  - metallb.yaml
  - metrics-server.yaml
  - reflector.yaml
  - sealed-secrets.yaml
  - traefik.yaml
  - cloudnativepg.yaml
  - authentik.yaml
